name: Deploy Presentation to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Presentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write 

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Pandoc (used to convert markdown to HTML)
      - name: Set up Pandoc
        run: |
          sudo apt-get install pandoc

      # Convert Markdown to HTML
      - name: Convert Markdown to HTML
        run: |
          pandoc -s README.md -o index.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
          
